language: go
sudo: false
go:
- 1.10.x
- 1.9.x
install:
- go get -t ./...
- git clone https://github.com/nats-io/gnatsd.git vendor/github.com/nats-io/gnatsd;
- cd vendor/github.com/nats-io/gnatsd;
- git checkout jwt;
- go install ./...
- cd ../../../..
- go get github.com/nats-io/nkeys
- go get github.com/nats-io/jwt
- go get github.com/mattn/goveralls
- go get github.com/wadey/gocovmerge
- go get -u honnef.co/go/tools/cmd/megacheck
- go get -u github.com/client9/misspell/cmd/misspell
before_script:
- $(exit $(go fmt ./... | wc -l))
- go vet ./...
- misspell -error -locale US .
- megacheck -ignore "$(cat staticcheck.ignore)" ./...
script:
- go test -i -race ./...
- if [[ "$TRAVIS_GO_VERSION" == 1.9.* ]]; then ./scripts/cov.sh TRAVIS; else go test -v -race ./...; fi
